export enum AT {
    FETCH_POSTS = "FETCH_POSTS",
    FETCH_TAGS = "FETCH_TAGS",
    FETCH_SINGLE = "FETCH_SINGLE",

    SELECT_FILTER = "SELECT_FILTER",
    FILTER_POSTS = "FILTER_POSTS",
    RESET_FILTER = "RESET_FILTER"
}